/* All default sounds are local. Change paths and rerun scripts/audio-bank.mjs. */
Defuse.assets = {
  bomb: "",
  button: "",
  background: "",
  smoke: "",
  gameAudio: {
    title: "Counter-Strike 2",
    artist: "Valve",
    cover: "assets/music/cs2-logo.svg",
  },
  tools: {
    pliers: "",
    wrench: "",
    screwdriver: "",
    rice: "",
    mouse: "",
    knife: "",
  },
  sounds: {
    tap: "assets/audio/click.wav",
    uiTap: "assets/audio/ui-click.wav",
    plant: "assets/audio/plant.wav",
    initiate: "assets/audio/initiate.wav",
    planted: "assets/audio/bomb-planted.mp3",
    shot: "assets/audio/opening-shot.wav",
    deagle: "assets/audio/deagle-shot.wav",
    footstep: "assets/audio/footstep.wav",
    teamHit: "assets/audio/team-hit.wav",
    teamHandoff: "assets/audio/team-handoff.wav",
    death: "assets/audio/death.mp3",
    distant: "assets/audio/distant-shot.wav",
    defuse: "assets/audio/defuse-start.wav",
    finish: "assets/audio/defuse-finish.wav",
    alarm: "assets/audio/beep.wav",
    urgent: "assets/audio/beep-urgent.wav",
    explosion: "assets/audio/explosion.mp3",
    smoke: "assets/audio/smoke.wav",
    flashPin: "assets/audio/flash-pin.wav",
    flashPop: "assets/audio/flash-pop.wav",
    flashRing: "assets/audio/flash-ring.wav",
    radio: "assets/audio/radio.mp3",
    ctwin: "assets/audio/ct-win.mp3",
    twin: "assets/audio/t-win.mp3",
    key1: "assets/audio/key-1.mp3",
    key2: "assets/audio/key-2.mp3",
    key3: "assets/audio/key-3.mp3",
    key4: "assets/audio/key-4.mp3",
    key5: "assets/audio/key-5.mp3",
    key6: "assets/audio/key-6.mp3",
    key7: "assets/audio/key-7.mp3",
    musicPlanted: "assets/audio/under-bright-lights-planted.mp3",
    musicTen: "assets/audio/under-bright-lights-ten.mp3",
    hualianPlanted: "assets/audio/hualian-planted.mp3",
    hualianTen: "assets/audio/hualian-ten.mp3",
    brightMvp: "assets/audio/under-bright-lights-mvp.mp3",
    hualianMvp: "assets/audio/hualian-mvp.mp3",
    knock2Planted: "assets/audio/knock2-planted.mp3",
    knock2Ten: "assets/audio/knock2-ten.mp3",
    knock2Mvp: "assets/audio/knock2-mvp.mp3",
    michaelPlanted: "assets/audio/killer-mike-planted.mp3",
    michaelTen: "assets/audio/killer-mike-ten.mp3",
    michaelMvp: "assets/audio/killer-mike-mvp.mp3",
  },
  musicKits: {
    bright: {
      title: "万众瞩目",
      artist: "TWERL 和 Ekko & Sidetrack",
      cover: "assets/music/under-bright-lights.webp",
      number: "01",
      tracks: { planted: "musicPlanted", ten: "musicTen" },
      mvp: "brightMvp",
    },
    hualian: {
      title: "花脸",
      artist: "完美世界",
      cover: "assets/music/hualian.webp",
      number: "02",
      tracks: { planted: "hualianPlanted", ten: "hualianTen" },
      mvp: "hualianMvp",
    },
    knock2: {
      title: "冲击星*",
      artist: "Knock2",
      cover: "assets/music/knock2-transparent.webp",
      number: "03",
      tracks: { planted: "knock2Planted", ten: "knock2Ten" },
      mvp: "knock2Mvp",
    },
    michael: {
      title: "迈克尔",
      artist: "Killer Mike",
      cover: "assets/music/killer-mike.png",
      number: "04",
      tracks: { planted: "michaelPlanted", ten: "michaelTen" },
      mvp: "michaelMvp",
    },
  },
};
Defuse.assetImage = (path, className, alt = "") => {
  const image = document.createElement("img");
  image.src = path;
  image.className = className;
  image.alt = alt;
  image.addEventListener("error", () => image.remove(), { once: true });
  return image;
};
